name: release

on:
  push:
    tags:
      - "v*.*.*"
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
              
      - uses: actions/checkout@v3
        with:
          lfs: true
      
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-Pong-Windows
          restore-keys: |
            Library-Pong-
            Library-

      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows

      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build


  release:
    needs: [build]
    runs-on: ubuntu-latest
    # Only run the release job if a tag has been pushed
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: build

      - uses: softprops/action-gh-release@v1
        with:    
          fail_on_unmatched_files: true
          files: |
            build/**